### ISSUE TITLE
CI pipeline for APK generation 

### ISSUE THREAD

**Issue by krutarth4** [Smoothex/cloud-based-traffic-light-assistant#5]
* Create a Pipeline either in github or Jenkins to support APK creation direcly from the master folder

**Comment by Smoothex** [comment]
I have some experience with GitHub Actions, so I'll gladly look into this. Will probably not be the very first priority, but it's good to have the issue already 👍🏻

**Comment by Smoothex** [comment]
Pipeline created and tested. It runs through and the .apk generated from it also works on a physical android device.
